<?php
/**
 * Created by PhpStorm.
 * User: wangy
 * Date: 26/12/2016
 * Time: 01:57
 */
namespace Sistr;

use F3il\Form;
use F3il\Field;

defined('SISTR') or die('Acces interdit');

class UtilisateurForm extends Form{

    public function __construct($action)
    {
        parent::__construct($action, 'utilisateur-creer');
        $this->addFormField(new \F3il\Field('id', 'Id', null, true));
        $this->addFormField(new \F3il\Field('nom', 'Nom', null, true));
        $this->addFormField(new \F3il\Field('prenom', 'Prenom', null, true));
        $this->addFormField(new \F3il\Field('email', 'Email', null, true));
        $this->addFormField(new \F3il\Field('login', 'Login', null, true));
        $this->addFormField(new \F3il\Field('motdepasse', 'Motdepasse', null, true));
        $this->addFormField(new \F3il\Field('confirmation', 'Confirmation', null, true));
    }

    public function messageRenderer($message)
    {
        ?>
        <p class="text-danger text-right"><?php echo $message; ?></p>
        <?php
    }

    public function missingFieldMessageRenderer($field)
    {
//        return parent::missingFieldMessageRenderer($field); // TODO: Change the autogenerated stub
        $label=strtolower($field->label);
        return "Veuillez remplir le champ $label.";
    }
}